apiVersion: v1
kind: Secret
metadata:
  name: nestjsops-db-secret
  namespace: nestjsops
type: Opaque
stringData:
  DB_HOST: 'simple-backend-db.abcd123.us-west-2.rds.amazonaws.com' # Replace with your RDS endpoint from Terraform output
  DB_PORT: '5432'
  DB_USERNAME: 'admin'
  DB_PASSWORD: 'SecurePass123!' # Replace with your secure password
  DB_NAME: 'postgres'
