apiVersion: v1
kind: Service
metadata:
  name: nestjsops-service
  namespace: nestjsops
spec:
  type: ClusterIP # Use LoadBalancer for external access (adds ALB cost)
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: nestjsops
